# Generated by Django 6.0.6 on 2026-07-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genesisapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subjecy',
            new_name='subject',
        ),
    ]
